### ISSUE TITLE
how to identify which function is unused?

### ISSUE THREAD

**Issue by jacobjiangwei** [alicialy/LTAppThinningScript#1]
To prove your script's integrity, i create a very simple swift project with two function, one is unused, one is called in viewDidLoad function.

I don't see too much differences from the output of result:

node linkmap_ext.js /Users/jacob/Library/Developer/Xcode/DerivedData/jkdf-bctycnfuafksiycxbakxucloeviq/Build/Intermediates/jkdf.build/Debug-iphonesimulator/jkdf.build/jkdf-LinkMap-normal-x86_64.txt -hu
AppDelegate.o	15.00KB
ViewController.o	2.67KB
jkdf.app.xcent	378B
libswiftCore.dylib	312B
libobjc.dylib	144B
libswiftFoundation.dylib	72B
libswiftObjectiveC.dylib	24B
UIKit	24B
libSystem.dylib	24B
Foundation	24B
linker synthesized	0B

LMXMN024:LTAppThinningScript jacob$ node linkmap_ext.js /Users/jacob/Library/Developer/Xcode/DerivedData/jkdf-bctycnfuafksiycxbakxucloeviq/Build/Intermediates/jkdf.build/Debug-iphonesimulator/jkdf.build/jkdf-LinkMap-normal-x86_64.txt -hu
AppDelegate.o	15.00KB
ViewController.o	3.26KB
libswiftCore.dylib	408B
jkdf.app.xcent	378B
libobjc.dylib	144B
libswiftFoundation.dylib	72B
libSystem.dylib	24B
libswiftSwiftOnoneSupport.dylib	24B
libswiftObjectiveC.dylib	24B
Foundation	24B
UIKit	24B
linker synthesized	0B

ViewController.o	2.67KB
increase to 
ViewController.o	3.26KB

but which function is unused? should i look into the linkMap again?
Your help is much appriciated.

**Comment by alicialy** [comment]
This script is for find unused class, not for find unused function, maybe you need this https://github.com/ming1016/SMCheckProject

**Comment by jacobjiangwei** [comment]
Not true, we found several class definitely in use

However the size of class was interesting

**Comment by JakeOrange** [comment]
按照目录路径没发现XXX-LinkMap-normal-arm64.txt呀，请问你的XCode是什么版本呀？

**Comment by alicialy** [comment]
@JakeOrange  设置 Project -> Build Settings -> Write Link Map File 为 YES
楼上写的地址是楼上的环境

配置的全文看这里 http://alicialy.github.io/2017/04/07/iOS-App-Thinning/
